import * as THREE from "three";

export const GLTFTypes = {
  nodes: {
    simple_modern_computer_desk_pasted__phong6_0001: new THREE.Mesh(),
    Object_2: new THREE.Mesh(),
    Keyboard: new THREE.Mesh(),
    Mouse: new THREE.Mesh(),
    mac: new THREE.Mesh(),
    ["mac-stander"]: new THREE.Mesh(),
    ["mac-screen"]: new THREE.Mesh(),
    React: new THREE.Mesh(),
    ["React-Book"]: new THREE.Mesh(),
    Tarbouch: new THREE.Mesh(),
    ["Tarbouch-Khoyout"]: new THREE.Mesh(),
    khayt1: new THREE.Mesh(),
    khayt2: new THREE.Mesh(),
    khayt3: new THREE.Mesh(),
    Cube: new THREE.Mesh(),
    Cube002: new THREE.Mesh(),
    Cube003: new THREE.Mesh(),
    ["React-Book001"]: new THREE.Mesh(),
    ["React-Book002"]: new THREE.Mesh(),
    ["React-Book003"]: new THREE.Mesh(),
    ["React-Book004"]: new THREE.Mesh(),
    WallBoard: new THREE.Mesh(),
    Paper1: new THREE.Mesh(),
    PaperFixer: new THREE.Mesh(),
    PaperFixer2: new THREE.Mesh(),
    PaperFixer3: new THREE.Mesh(),
    Paper1001: new THREE.Mesh(),
    Paper1002: new THREE.Mesh(),
    Cube001: new THREE.Mesh(),
    Cube004: new THREE.Mesh(),
    Cube005: new THREE.Mesh(),
    Cube006: new THREE.Mesh(),
    Cube007: new THREE.Mesh(),
    Cube008: new THREE.Mesh(),
  },
  materials: {},
};
